### ISSUE TITLE
QoL ?Bug?

### ISSUE THREAD

**Issue by Dean-Gallagher** [KingMarcel/hk_issues#13]
Sers, 

wenn man eine Antwort von der HK bekommt sieht es so aus in der Benachritungsübersicht und die Benachrichtigung selbst 
https://pic.statev.de/image/grafik.wYW0Y

klickt man drauf kommt man nur in sein Postfach. Dort sucht man dann vergeblich nach der nummer aus der Benachrichtung. Man muss also ALLE schreiben per hand öffnen und einsehen. 

https://pic.statev.de/image/grafik.wYgdz

Entweder ist ein Bug und wenn nicht, wäre es nicht vll sinnvoll das man direkt zu dem Schreiben kommt und nicht nur in die Übersicht? 

grüße

**Comment by KMDEV-Marcel** [comment]
Danke für das Feedback. Eine Spalte mit der ID ist nun vorhanden
